services:
  # --- INFRASTRUCTURE ---
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eRabbit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"   # Port de communication
      - "15672:15672" # Interface de gestion (Management)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # --- MICROSERVICES ---
  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/eRabbit_db?schema=public"
    depends_on:
      - db

  order-service:
    build: ./order-service
    container_name: order_service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/eRabbit_db?schema=public"
      RABBITMQ_URL: "amqp://rabbitmq"
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  payment-worker:
    build: ./payment-worker
    container_name: payment_worker
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/eRabbit_db?schema=public"
      RABBITMQ_URL: "amqp://rabbitmq"
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
